### ISSUE TITLE
Disable a display

### ISSUE THREAD

**Issue by denis-sokolov** [Kwpolska/DisplayMenu#1]
I love the option to quickly switch my display configuration, this tool is great. What I am also looking for is the ability to fully disable a particular display altogether. I think it’s not supported in this tool, but I wanted to make sure I didn’t miss it. Thank you!

**Comment by Kwpolska** [comment]
Can you manually turn a display off in System Preferences? I don’t see an option for this, and there doesn’t seem to be anything in the API, so I believe that might not be possible to do on macOS.

**Comment by denis-sokolov** [comment]
No, I can’t do it in System Preferences, it’s annoying. Oh well, thanks for taking a look!
